# Generated by Django 5.2.5 on 2025-12-11 14:44

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Merch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=1024)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MerchPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imgurl', models.CharField(max_length=256)),
                ('type', models.IntegerField(choices=[(1, 'MAIN'), (2, 'SECONDARY')], default='SECONDARY')),
                ('merch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecat.merch')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=datetime.datetime(2025, 12, 11, 17, 44, 40, 356680))),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('pk', models.CompositePrimaryKey('order_id', 'merch_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('merch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecat.merch')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecat.order')),
            ],
        ),
    ]
