# Generated by Django 5.2.5 on 2025-12-11 14:45

from django.db import migrations



def fillTestData(apps, schema_editor):
    Merch = apps.get_model("ecat", "Merch")
    MerchPhoto = apps.get_model("ecat", "MerchPhoto")

    merchIds = ("4ccb388c-6b2e-4d28-b037-3dccb702b774",
                "b431b555-f28e-4c51-8cb2-82125bdc7e56",
                "4befc90c-b60d-4391-82c2-6eff62c199ba",
                "9e4bc16d-c518-4f11-9898-4af6684f64f5",
                "c3fc10b4-4aff-4f22-8a36-ec71d76804a3",
                "ddd50587-e72e-4bf3-94f3-6aec48b92d32",
                "e8e6396d-5e45-440d-8869-a906ac70095c",
                "3cb43d91-f370-4862-91b7-e8fbd79e3bc9",
                "5e01c30b-2acb-4bd9-a44d-383cb900776e",
                "3430d02a-7ab5-4b86-9cca-a34d4e7edd96",
                "24ceb2a7-0ef0-4e40-bd0f-394bca9f04c1",
                "d7f49f9c-3d22-4c3d-9f4d-c71832b9d088",
                "58beb166-6779-4e16-8103-e7116fbe128a",
                "7c850b2c-880f-43f1-b39a-fa89ab59bd32",
                "e4a2daa2-a121-4f0a-bc87-78cc30de568f",
                "de9b0619-8c81-400f-997e-afd6ea2b5738",
                "fcf455d7-db7b-4f6f-83d2-83c267ea5fed",
                "a4bdf432-0ab8-4c7a-b574-5df73f23bcab",)
    
    merchTitles = ("Штанга",
                "Бейсбольный мяч",
                "Бейсбольная бита",
                "Баскетбольный мяч",
                "Велосипед",
                "Боксёрские перчатки",
                "Маска для дайвинга" ,
                "Гантеля",
                "Ласты",
                "Кроссовки",
                "Купальник",
                "Волейбольный мяч",
                "Боксёрские перчатки",
                "Велосипедный шлем",
                "Ледовые коньки",
                "Теннисная ракетка",
                "Скейтборд",
                "Напульсник",)
    
    merchDescriptions = ("Отличная штанга для занятий тяжёлой атлетикой (два диска по 20 кг в комплекте)",
                    "Импортный бейсбольный мяч. Вес 150г",
                    "Материал: бук. Длина 1м.",
                    "Баскетбольный мяч фирмы MILC. Цвет: оранжевый",
                    "Прогулочный велосипед для взрослых. Ободные тормоза. 18 передач",
                    "Натуральная кожа. Синтетический наполнитель",
                    "Закалённое стекло. Выдерживает глубины до 1000м ",
                    "Гантеля 4кг. Красный цвет",
                    "Ласты для плавания. В комплекте 3шт (1 запасная)",
                    "Многофункциональные кроссовки. Подходят для спорта и прогулок. ",
                    "Женский купальник чёрного цвета. Размер L",
                    "Волейбольный мяч кустарного производства. Соответствует основным спецификациям",
                    "Кожаные перчатки как для любительского, так и для профессионального занятия боксом",
                    "Прочный велосипедный шлем из полимерных материалов. Обеспечивает лёгкость и прочность одновременно",
                    "Коньки для фигурного катания. Утеплены, подходят для катания при температурах до -10",
                    "Теннисная ракетка для большого тенниса. Для маленького не подходит. Мяч не входит в комплект",
                    "Любительский скейтборд. Выдерживает вес подростка до 110 кг",
                    "Незаменимый полезный аксессуар для всех тех кто пытается заниматься спортом"
                    )

    merchPrices = [8000.0,
                150.0,
                1500.0,
                1800.0,
                15000.0,
                500.0,
                5000.0,
                900.0,
                2000.0,
                3000.0,
                2000.0,
                1500.0,
                1000.0,
                800.0,
                600.0,
                320.0,
                690.0,
                45.0]
    
    merchQuantity = (  5,
                        100,
                        30,
                        5,
                        1,
                        5,
                        3,
                        5,
                        6,
                        10,
                        10,
                        10,
                        5,
                        3,
                        5,
                        20,
                        8,
                        50)
    
    merchPhotoIds = ("42af04ec-0312-484a-8cfe-d17792d8b962",
        "0b1c44b3-5751-47e2-901b-dc4dbc2a72ba",     
        "e329c0bb-f59c-4aca-9795-ed60d4f94eeb",
        "c03f6737-5b07-4bd4-a333-d46c1848d967",
        "23e6fd5d-ff8a-4dc4-8d7f-359d53ca1158",
        "aee611b7-2c4f-435b-8b99-5eff406bd78b",
        "162dcb4d-81f3-4e51-8037-ec32e62f515f",
        "b5dc336e-8ff6-4ddd-980e-eb82d7750263",
        "bbf27716-19f7-4d3a-9d6e-8fccc17df3a9",
        "ed9f142a-4e49-4066-9739-eab174e3fab7",
        "dec28f7b-6c46-466e-b15a-5b71f85b9b75",
        "575bb21f-0774-4be0-a98a-ff2d385f3c48",
        "0a95c20c-169e-46eb-987d-8e2bf280a272",
        "0f3fbb9f-e98d-4ffb-8f26-c72fb778c181",
        "33a63637-d50e-494d-ba5b-3048bfbf01aa",
        "8e4f7da7-b552-4629-8536-edc984dd5b04",
        "843a0fa7-c4bd-4e6d-97f1-d62788f59943",
        "97c8a468-780c-432f-a231-9f5932d23670",)
    
    merchPhotoUrls =("/b'TMs4jGsuTSiwNz3MtwK3dA=='/b'Qq8E7AMSSEqM_tF3kti5Yg=='.jpg",
            "/b'tDG1VfKOTFGMsoISW9x-Vg=='/b'CxxEs1dRR-KQG9xNvCpyug=='.jpg",
            "/b'S-_JDLYNQ5GCwm7_YsGZug=='/b'4ynAu_WcSsqXle1g1PlO6w=='.jpg",
            "/b'nkvBbcUYTxGYmEr2aE9k9Q=='/b'wD9nN1sHS9SjM9RsGEjZZw=='.jpg",
            "/b'w_wQtEr_TyKKNuxx12gEow=='/b'I-b9Xf-KTcSNfzWdU8oRWA=='.jpg",
            "/b'3dUFh-cuS_OU82rsSLktMg=='/b'ruYRtyxPQ1uLmV7_QGvXiw=='.jpg",
            "/b'6OY5bV5FRA2IaakGrHAJXA=='/b'Fi3LTYHzTlGAN-wy5i9RXw=='.jpg",
            "/b'PLQ9kfNwSGKRt-j71547yQ=='/b'tdwzbo_2Td2YDuuC13UCYw=='.jpg",
            "/b'XgHDCyrLS9mkTTg8uQB3bg=='/b'u_J3Fhn3TTqdbo_MwX3zqQ=='.jpg",
            "/b'NDDQKnq1S4acyqNNTn7dlg=='/b'7Z8UKk5JQGaXOeqxdOP6tw=='.jpg",
            "/b'JM6ypw7wTkC9DzlLyp8EwQ=='/b'3sKPe2xGRm6xWltx-FubdQ=='.jpg",
            "/b'1_SfnD0iTD2fTccYMrnQiA=='/b'V1uyHwd0S-Cpiv8tOF88SA=='.jpg",
            "/b'WL6xZmd5ThaBA-cRb74Sig=='/b'CpXCDBaeRuuYfY4r8oCicg=='.jpg",
            "/b'fIULLIgPQ_GzmvqJq1m9Mg=='/b'Dz-7n-mNT_uPJscvt3jBgQ=='.jpg",
            "/b'5KLaoqEhTwq8h3jMMN5Wjw=='/b'M6Y2N9UOSU26WzBIv78Bqg=='.jpg",
            "/b'3psGGYyBQA-Zfq_W6itXOA=='/b'jk99p7VSRimFNu3JhN1bBA=='.jpg",
            "/b'_PRV19t7T2-D0oPCZ-pf7Q=='/b'hDoPp8S9Tm2X8dYniPWZQw=='.jpg",
            "/b'pL30Mgq4THq1dF33PyO8qw=='/b'l8ikaHgMQy-iMZ9ZMtI2cA=='.jpg",)
    

    for i, x in enumerate(merchIds):
        merch1 = Merch.objects.create(id=x, title=merchTitles[i], description=merchDescriptions[i], price=merchPrices[i], quantity = merchQuantity[i])
        merch1.save()
        merchPhoto1 = MerchPhoto.objects.create(id=merchPhotoIds[i], imgurl=merchPhotoUrls[i], type=1, merch=merch1)
        merchPhoto1.save()




class Migration(migrations.Migration):

    dependencies = [
        ('ecat', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(fillTestData)
    ]