# Generated by Django 5.2.5 on 2025-12-11 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfirmCode',
            fields=[
                ('id', models.CharField(default='', editable=False, max_length=100, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=datetime.datetime(2025, 12, 11, 17, 44, 40, 358623))),
                ('code', models.IntegerField(default=721358)),
            ],
        ),
    ]
