name: arfema-db

services:
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=0451
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

volumes:
  db-data:
    name: "arfema-data"
      